INFRA: Initialize Unit Tests Project
hassanhabib/InternTrack.Core pull request #13
Opened 2023-04-28 21:15 UTC by ADILATIC

2023-04-28 23:31 UTC, glhays requested changes
@ADILATIC please see the review comment and correct. Good job this is much better.
You now have two Pull Requests open for the same task, @hassanhabib should he close the other one himself?

2023-04-28 23:31 UTC, glhays commented on Intern.Core.Api.Tests.Unit/DeleteMe.cs
> +
@ADILATIC Remove extra line here.

2023-04-28 23:31 UTC, glhays commented on Intern.Core.Api.Tests.Unit/Usings.cs
> +global using Xunit;
@ADILATIC Remove this file. In the VS add project dialog there is a setting you need to uncheck, this file is automatically created. We do not use Global usings.

2023-04-28 23:37 UTC, glhays commented on Intern.Core.Api.Tests.Unit/Usings.cs
> +global using Xunit;
@ADILATIC All you need to do now is delete it and commit the change on this branch.

2023-04-28 23:43 UTC, glhays commented
@ADILATIC What issue does this close?
If you review the closed pull requests across Hassan's repositories you will see how it is done.
Sample:
![Screenshot 2023-04-22 123338](https://user-images.githubusercontent.com/42452283/235270333-d6c6a138-6b77-48d6-9e3c-f15216e320a6.jpg)

2023-04-28 23:45 UTC, ADILATIC commented
I didn't fully complete I was following the video . And that's where I created this pr.

2023-04-29 06:41 UTC, hassanhabib commented
> @ADILATIC please see the review comment and correct. Good job this is much better. You now have two Pull Requests open for the same task, @hassanhabib should he close the other one himself?

I closed it @glhays

2023-04-29 19:07 UTC, glhays commented
> I didn't fully complete I was following the video . And that's where I created this pr.

@ADILATIC I am not sure if this comment relates to my close comment but assuming it is.
I think you are confused some what, my comment relates to closing the ISSUE your Pull Request relates to. Your Issue is the Unit Test Initialization, So if you type in your comment box, Closes then a space, then a hash, you will get a popup listing the open issues. You can select or enter the issue number, When this pull request is merged it closes that issue by linking the PR to the Issue.

2023-04-30 19:35 UTC, hassanhabib commented on Intern.Core.Api.Tests.Unit/DeleteMe.cs
> +
Remove extra line here

2023-04-30 21:06 UTC, merged